const REVIEW_MODE=true;
const STATE={data:window.YT_DATA,page:(location.hash||'#overview').slice(1),contentType:'all',contentSort:'views',contentSearch:'',topicMetric:'momentum',selectedTopic:null,scheduleType:'Shorts'};
const PAGE_META={overview:['Обзор канала','YouTube Studio · ключевые показатели'],themes:['Темы Shorts','Потенциал тем · 365 дней'],content:['Контент','Все ролики · 365 дней'],rhythm:['Ритм публикаций','Последние 90 дней'],schedule:['День и время','Эффективность публикаций · 365 дней'],growth:['План роста','Слабые места и действия · 30 дней']};
const COLORS=['#2563eb','#ff3b30','#16a36a','#7c3aed','#f59e0b','#06b6d4'];
const DAYS=['Понедельник','Вторник','Среда','Четверг','Пятница','Суббота','Воскресенье'];
const nf=new Intl.NumberFormat('ru-RU');
const shortN=(n)=>{n=Number(n)||0;if(n>=1e6)return`${(n/1e6).toFixed(n>=1e7?0:1).replace('.',',')} млн`;if(n>=1e3)return`${(n/1e3).toFixed(n>=1e5?0:1).replace('.',',')} тыс.`;return nf.format(Math.round(n))};
const pct=(n,d=1)=>`${(Number(n)*100).toFixed(d).replace('.',',')}%`;
const pctRaw=(n,d=1)=>`${Number(n).toFixed(d).replace('.',',')}%`;
const avg=a=>a.length?a.reduce((s,v)=>s+(Number(v)||0),0)/a.length:0;
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmtDate=iso=>new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'long',year:'numeric'}).format(new Date(`${iso}T00:00:00Z`));
const duration=s=>{s=Math.round(Number(s)||0);const h=Math.floor(s/3600),m=Math.floor(s%3600/60),x=s%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(x).padStart(2,'0')}`:`${m}:${String(x).padStart(2,'0')}`};

function all365(){return [...STATE.data.shorts365,...STATE.data.videos365]}
function splitTopics(row){return String(row.topic||'Другое').split(',').map(s=>s.trim()).filter(Boolean)}
function aggregateTopics(rows){
  const map=new Map();
  rows.forEach(r=>splitTopics(r).forEach(topic=>{if(!map.has(topic))map.set(topic,[]);map.get(topic).push(r)}));
  return [...map].map(([topic,items])=>({topic,count:items.length,avgViews:avg(items.map(x=>x.views)),momentum:avg(items.filter(x=>x.ageDays>=10).map(x=>x.momentum)),retention:avg(items.map(x=>x.retention)),ctr:avg(items.map(x=>x.ctr)),totalViews:items.reduce((s,x)=>s+x.views,0),items}));
}
function weeklyData(){
  const map=new Map();
  STATE.data.content90.filter(r=>r.fresh&&r.published).forEach(r=>{const d=new Date(`${r.published}T00:00:00Z`);const day=(d.getUTCDay()+6)%7;d.setUTCDate(d.getUTCDate()-day);const key=d.toISOString().slice(0,10);if(!map.has(key))map.set(key,{date:key,Shorts:0,Видео:0});map.get(key)[r.type]=(map.get(key)[r.type]||0)+1});
  return [...map.values()].sort((a,b)=>a.date.localeCompare(b.date));
}
function weekdayAgg(type){
  const rows=type==='Shorts'?STATE.data.shorts365:STATE.data.videos365;
  return DAYS.map(day=>{const items=rows.filter(r=>r.weekday===day);const fresh=STATE.data.content90.filter(r=>r.type===type&&r.fresh&&r.weekday===day);return{day,count:items.length,momentum:avg(items.filter(x=>x.ageDays>=10).map(x=>x.momentum)),retention:avg(items.map(x=>x.retention)),published:fresh.length}});
}
function kpi(label,value,delta,down=false,icon='↗'){return`<article class="card kpi"><div class="kpi-top"><span class="kpi-label">${label}</span><span class="kpi-icon">${icon}</span></div><div class="kpi-value">${value}</div><div class="delta ${down?'down':'up'}">${delta}</div></article>`}
function panelHead(title,subtitle='',right=''){return`<div class="panel-head"><div><h2>${title}</h2>${subtitle?`<p>${subtitle}</p>`:''}</div>${right}</div>`}
function donut(items){
  const total=items.reduce((s,x)=>s+x.value,0);let p=0;const stops=items.map((x,i)=>{const a=p/total*100;p+=x.value;return`${COLORS[i%COLORS.length]} ${a}% ${p/total*100}%`}).join(',');
  return`<div class="donut-layout"><div class="donut" style="background:conic-gradient(${stops})"><div class="donut-center"><strong>${shortN(total)}</strong><span>просмотров</span></div></div><div class="donut-list">${items.map((x,i)=>`<div class="donut-row"><i class="dot" style="background:${COLORS[i]}"></i><span>${esc(x.label)}</span><span>${pct(x.value/total,1)}</span></div>`).join('')}</div></div>`;
}
function barList(data,valueKey,formatter=shortN,limit=8,green=false){const top=[...data].sort((a,b)=>b[valueKey]-a[valueKey]).slice(0,limit),max=Math.max(...top.map(x=>x[valueKey]),1);return`<div class="bar-list">${top.map(x=>`<div class="bar-row"><div class="bar-label" title="${esc(x.topic||x.label)}">${esc(x.topic||x.label)}</div><div class="bar-track"><div class="bar-fill ${green?'green':''}" style="width:${Math.max(2,x[valueKey]/max*100)}%"></div></div><div class="bar-value">${formatter(x[valueKey])}</div></div>`).join('')}</div>`}
function bubbleLayout(data,maxX,maxY,maxC){
  const W=500,H=350,nodes=data.slice(0,15).map((item,i)=>{const size=38+Math.sqrt(item.count/maxC)*34,tx=28+Math.log10(item.totalViews+1)/Math.log10(maxX+1)*(W-60),ty=24+item.momentum/maxY*(H-54);return{item,i,size,r:size/2,tx,ty,x:tx,y:ty}});
  for(let step=0;step<140;step++){
    for(let i=0;i<nodes.length;i++)for(let j=i+1;j<nodes.length;j++){const a=nodes[i],b=nodes[j],dx=b.x-a.x,dy=b.y-a.y,dist=Math.hypot(dx,dy)||.01,min=a.r+b.r+5;if(dist<min){const push=(min-dist)/2,nx=dist>.02?dx/dist:Math.cos(i+j),ny=dist>.02?dy/dist:Math.sin(i+j);a.x-=nx*push;a.y-=ny*push;b.x+=nx*push;b.y+=ny*push}}
    nodes.forEach(n=>{n.x+=(n.tx-n.x)*.025;n.y+=(n.ty-n.y)*.025;n.x=Math.max(n.r+4,Math.min(W-n.r-4,n.x));n.y=Math.max(n.r+4,Math.min(H-n.r-4,n.y))});
  }
  return nodes.map(n=>({...n,left:n.x/W*100,bottom:n.y/H*100}));
}
function lineChart(series){
  const W=760,H=250,pad={l:38,r:14,t:18,b:28};const values=series.flatMap(s=>s.values);const max=Math.max(...values,1);const count=Math.max(...series.map(s=>s.values.length));const x=i=>pad.l+(W-pad.l-pad.r)*(i/(Math.max(count-1,1)));const y=v=>H-pad.b-(H-pad.t-pad.b)*(v/max);
  const grids=[0,.25,.5,.75,1].map(t=>`<line class="grid-line" x1="${pad.l}" y1="${y(max*t)}" x2="${W-pad.r}" y2="${y(max*t)}"/><text class="axis-label" x="0" y="${y(max*t)+3}">${Math.round(max*t)}</text>`).join('');
  const lines=series.map((s,si)=>`<polyline fill="none" stroke="${s.color}" stroke-width="2.5" stroke-linejoin="round" points="${s.values.map((v,i)=>`${x(i)},${y(v)}`).join(' ')}"/>${s.values.map((v,i)=>`<circle cx="${x(i)}" cy="${y(v)}" r="3" fill="${s.color}"><title>${s.labels?.[i]||i}: ${v}</title></circle>`).join('')}`).join('');
  const labels=(series[0].labels||[]).map((l,i)=>i%2===0||count<10?`<text class="axis-label" text-anchor="middle" x="${x(i)}" y="${H-7}">${esc(l)}</text>`:'').join('');
  return`<svg class="svg-chart" viewBox="0 0 ${W} ${H}" role="img" aria-label="График публикаций по неделям">${grids}${lines}${labels}</svg>`;
}
function contentTable(rows,limit=10){return`<div class="table-wrap"><table class="data-table"><thead><tr><th>#</th><th>Ролик</th><th>Тип</th><th>Просмотры</th><th>Momentum</th><th>CTR</th><th>Retention</th><th>Дата</th></tr></thead><tbody>${rows.slice(0,limit).map((r,i)=>`<tr><td class="rank">${i+1}</td><td class="title-cell"><strong title="${esc(r.title)}">${esc(r.title)}</strong><span>${esc(splitTopics(r).slice(0,2).join(' · '))}</span></td><td><span class="pill ${r.type==='Shorts'?'short':''}">${esc(r.type)}</span></td><td><strong>${shortN(r.views)}</strong></td><td>${r.momentum?nf.format(Math.round(r.momentum)):'—'}</td><td>${pctRaw(r.ctr,2)}</td><td>${pct(r.retention,1)}</td><td>${new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'short',year:'2-digit'}).format(new Date(`${r.published}T00:00:00Z`))}</td></tr>`).join('')}</tbody></table></div>`}

function renderOverview(){
  const d=STATE.data,w=d.weak,weeks=weeklyData(),labels=weeks.map(x=>new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'short'}).format(new Date(`${x.date}T00:00:00Z`)));
  const themes=aggregateTopics(d.shorts365);
  return`<div class="kpi-grid">${kpi('Просмотры · 90 дней',shortN(d.studio90.views),d.studio90.viewsDelta,false,'◉')}${kpi('Время просмотра',`${shortN(d.studio90.watchHours)} ч`,d.studio90.watchDelta,true,'◷')}${kpi('Новые подписчики',`+${nf.format(d.studio90.subscribers)}`,d.studio90.subscribersDelta,true,'＋')}${kpi('Конверсия в подписку',pct(w.conversion,3),'цель: 0,50%',true,'↗')}</div>
  <div class="grid-2"><article class="card panel">${panelHead('Просмотры по типу контента','365 дней · полный отчёт')} ${donut(d.overview365.map(x=>({label:x.type,value:x.views})))}</article><article class="card panel">${panelHead('Публикации по неделям','синие — Shorts, жёлтые — видео',`<div class="legend"><span><i style="background:${COLORS[0]}"></i>Shorts</span><span><i style="background:${COLORS[4]}"></i>Видео</span></div>`)}${lineChart([{values:weeks.map(x=>x.Shorts),labels,color:COLORS[0]},{values:weeks.map(x=>x.Видео),labels,color:COLORS[4]}])}<div class="insight"><span>↗</span><div><strong>Средний темп: ${avg(weeks.map(x=>x.Shorts)).toFixed(1).replace('.',',')} Shorts и ${avg(weeks.map(x=>x.Видео)).toFixed(1).replace('.',',')} видео в неделю.</strong><br>Целевой ритм — 6–7 Shorts и не меньше 2 видео.</div></div></article></div>
  <div class="grid-2 grid-equal"><article class="card panel">${panelHead('Темы, которые дают охват','Shorts · суммарные просмотры')}${barList(themes,'totalViews',shortN,7)}</article><article class="card panel">${panelHead('Что требует внимания','сигналы за 90/365 дней')}<div class="bar-list"><div class="bar-row"><div class="bar-label">Видео с CTR ниже 4%</div><div class="bar-track"><div class="bar-fill" style="width:${w.lowCtrShare*100}%;background:#ff3b30"></div></div><div class="bar-value">${pct(w.lowCtrShare,0)}</div></div><div class="bar-row"><div class="bar-label">Видео с retention ниже 40%</div><div class="bar-track"><div class="bar-fill" style="width:${w.lowRetentionShare*100}%;background:#f59e0b"></div></div><div class="bar-value">${pct(w.lowRetentionShare,0)}</div></div><div class="bar-row"><div class="bar-label">Просмотры от архива</div><div class="bar-track"><div class="bar-fill" style="width:${(1-w.freshShare)*100}%;background:#7c3aed"></div></div><div class="bar-value">${pct(1-w.freshShare,0)}</div></div></div><div class="insight"><span>!</span><div><strong>Охват растёт быстрее подписной базы.</strong><br>При +30% просмотров подписчики снизились на 6% к предыдущему периоду.</div></div></article></div>`;
}

function renderThemes(){
  const data=aggregateTopics(STATE.data.shorts365).filter(x=>x.count>=2).sort((a,b)=>b[STATE.topicMetric]-a[STATE.topicMetric]);
  const selected=STATE.selectedTopic?data.find(x=>x.topic===STATE.selectedTopic):data[0];STATE.selectedTopic=selected?.topic;
  const maxX=Math.max(...data.map(x=>x.totalViews),1),maxY=Math.max(...data.map(x=>x.momentum),1),maxC=Math.max(...data.map(x=>x.count),1);
  const bubbles=bubbleLayout(data,maxX,maxY,maxC).map(({item:x,left,bottom,size})=>`<button class="bubble ${x.topic===STATE.selectedTopic?'active':''}" data-topic="${esc(x.topic)}" style="left:${left}%;bottom:${bottom}%;width:${size}px;height:${size}px" aria-label="${esc(x.topic)}, ${shortN(x.totalViews)} просмотров"><span>${esc(x.topic.replace(/\(.+?\)/g,''))}</span></button>`).join('');
  const metricOptions={momentum:'Momentum',totalViews:'Суммарные просмотры',avgViews:'Средние просмотры',retention:'Retention'};
  return`<div class="section-title"><div><h2>Где сейчас больше всего потенциала</h2><p>Размер круга — количество роликов, положение — охват и скорость набора просмотров</p></div><div class="controls"><select id="topic-metric">${Object.entries(metricOptions).map(([v,l])=>`<option value="${v}" ${STATE.topicMetric===v?'selected':''}>${l}</option>`).join('')}</select></div></div><div class="topic-layout"><article class="card panel">${panelHead('Карта тем Shorts','темы с двумя и более роликами')}<div class="bubble-chart"><span class="bubble-axis y">выше momentum ↑</span><span class="bubble-axis x">больше просмотров →</span>${bubbles}</div></article>${selected?`<article class="card topic-detail"><span class="pill short">Тема Shorts</span><h3>${esc(selected.topic)}</h3><p class="muted" style="font-size:11px">${selected.count<6?'Спрос уже виден, но выборка пока небольшая — хороший кандидат для теста серии.':'Проверенная тема с достаточным объёмом публикаций.'}</p><div class="detail-kpis"><div class="mini-stat"><span>Роликов</span><strong>${selected.count}</strong></div><div class="mini-stat"><span>Просмотров</span><strong>${shortN(selected.totalViews)}</strong></div><div class="mini-stat"><span>Momentum</span><strong>${nf.format(Math.round(selected.momentum))}/д</strong></div><div class="mini-stat"><span>Retention</span><strong>${pct(selected.retention,0)}</strong></div></div><h4 style="font-size:11px;margin:0">Лучшие ролики</h4><div class="topic-videos">${[...selected.items].sort((a,b)=>b.views-a.views).slice(0,4).map(r=>`<div class="video-mini"><div class="thumb">▶</div><div><strong title="${esc(r.title)}">${esc(r.title)}</strong><span>${pctRaw(r.ctr,1)} CTR · ${duration(r.duration)}</span></div><b>${shortN(r.views)}</b></div>`).join('')}</div></article>`:''}</div>
  <article class="card panel" style="margin-top:16px">${panelHead('Рейтинг тем',`Сортировка: ${metricOptions[STATE.topicMetric]}`)}${barList(data,STATE.topicMetric,STATE.topicMetric==='retention'?x=>pct(x,0):STATE.topicMetric==='momentum'?x=>`${nf.format(Math.round(x))}/д`:shortN,12,true)}</article>`;
}

function renderContent(){
  let rows=all365();if(STATE.contentType!=='all')rows=rows.filter(r=>r.type===STATE.contentType);if(STATE.contentSearch)rows=rows.filter(r=>(r.title+' '+r.topic).toLowerCase().includes(STATE.contentSearch.toLowerCase()));rows.sort((a,b)=>(b[STATE.contentSort]||0)-(a[STATE.contentSort]||0));
  const typeRows=STATE.contentType==='Shorts'?STATE.data.shorts365:STATE.contentType==='Видео'?STATE.data.videos365:all365();
  const themes=aggregateTopics(typeRows);
  return`<div class="kpi-grid">${kpi('Роликов в отчёте',nf.format(typeRows.length),'топ по просмотрам',false,'▶')}${kpi('Суммарные просмотры',shortN(typeRows.reduce((s,x)=>s+x.views,0)),'за 365 дней',false,'◉')}${kpi('Средний CTR',pctRaw(avg(typeRows.map(x=>x.ctr)),2),'по выбранному типу',false,'↗')}${kpi('Средний retention',pct(avg(typeRows.map(x=>x.retention)),1),'по выбранному типу',false,'◷')}</div><div class="grid-2 grid-equal"><article class="card panel">${panelHead('Темы по просмотрам','проверенные направления')}${barList(themes,'totalViews',shortN,8)}</article><article class="card panel">${panelHead('Темы по скорости','просмотров в день с публикации')}${barList(themes,'momentum',x=>`${nf.format(Math.round(x))}/д`,8,true)}</article></div>
  <div class="section-title" style="margin-top:24px"><div><h2>Каталог роликов</h2><p>${nf.format(rows.length)} материалов · поиск и сортировка</p></div><div class="controls"><div class="segmented" id="content-type">${[['all','Все'],['Shorts','Shorts'],['Видео','Видео']].map(([v,l])=>`<button data-value="${v}" class="${STATE.contentType===v?'active':''}">${l}</button>`).join('')}</div><input type="search" id="content-search" value="${esc(STATE.contentSearch)}" placeholder="Поиск по названию"><select id="content-sort"><option value="views" ${STATE.contentSort==='views'?'selected':''}>По просмотрам</option><option value="momentum" ${STATE.contentSort==='momentum'?'selected':''}>По momentum</option><option value="ctr" ${STATE.contentSort==='ctr'?'selected':''}>По CTR</option><option value="retention" ${STATE.contentSort==='retention'?'selected':''}>По retention</option></select></div></div>${contentTable(rows,24)}`;
}

function renderRhythm(){
  const weeks=weeklyData(),max=Math.max(...weeks.flatMap(x=>[x.Shorts,x.Видео]),1);const avgS=avg(weeks.map(x=>x.Shorts)),avgV=avg(weeks.map(x=>x.Видео));
  return`<div class="kpi-grid">${kpi('Shorts в неделю',avgS.toFixed(1).replace('.',','),'цель: 6–7',avgS<6,'▥')}${kpi('Видео в неделю',avgV.toFixed(1).replace('.',','),'цель: не менее 2',avgV<2,'▶')}${kpi('Всего в неделю',(avgS+avgV).toFixed(1).replace('.',','),'текущий темп',false,'＋')}${kpi('Свежий контент',pct(STATE.data.weak.freshShare,0),'доля просмотров за 90 дней',false,'↗')}</div><article class="card panel" style="margin-top:16px">${panelHead('Публикации по неделям','по дате выхода контента',`<div class="legend"><span><i style="background:${COLORS[0]}"></i>Shorts</span><span><i style="background:${COLORS[4]}"></i>Видео</span></div>`)}<div class="weekly-chart"><div class="target-line" style="bottom:${28+7/max*267}px"><span>ориентир Shorts: 7</span></div>${weeks.map(w=>`<div class="week-group"><div class="week-bar shorts" style="height:${w.Shorts/max*100}%"><title>${w.Shorts} Shorts</title></div><div class="week-bar video" style="height:${w.Видео/max*100}%"><title>${w.Видео} видео</title></div><span class="week-label">${new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'short'}).format(new Date(`${w.date}T00:00:00Z`))}</span></div>`).join('')}</div><div class="insight"><span>↗</span><div><strong>Свежий контент обеспечивает ${pct(STATE.data.weak.freshShare,0)} просмотров.</strong><br>Стабильность важнее пиков: удерживайте ежедневный ритм Shorts и два полноформатных выпуска.</div></div></article><div class="grid-2 grid-equal"><article class="card panel">${panelHead('Рекомендуемый недельный ритм','повторять каждую неделю')}<div class="table-wrap"><table class="data-table"><thead><tr><th>День</th><th>Shorts</th><th>Видео</th></tr></thead><tbody>${[['Пн','Core-тема','—'],['Вт','Тест новой темы','—'],['Ср','Core + momentum','1 core-видео'],['Чт','Core + momentum','1 видео · лучший день'],['Пт','Core-тема','—'],['Сб','Тест новой темы','—'],['Вс','Топ-momentum','—']].map(r=>`<tr><td><b>${r[0]}</b></td><td>${r[1]}</td><td>${r[2]}</td></tr>`).join('')}</tbody></table></div></article><article class="card panel">${panelHead('Распределение нагрузки','публикации свежего контента по дням')}${barList(DAYS.map(day=>{const s=STATE.data.content90.filter(r=>r.fresh&&r.weekday===day&&r.type==='Shorts').length,v=STATE.data.content90.filter(r=>r.fresh&&r.weekday===day&&r.type==='Видео').length;return{label:day,total:s+v}}),'total',nf.format,7)}</article></div>`;
}

function renderSchedule(){
  const data=weekdayAgg(STATE.scheduleType),best=[...data].sort((a,b)=>b.momentum-a.momentum)[0],worst=[...data].sort((a,b)=>a.momentum-b.momentum)[0],maxM=Math.max(...data.map(x=>x.momentum),1),maxP=Math.max(...data.map(x=>x.published),1);
  return`<div class="section-title"><div><h2>Когда контент набирает быстрее</h2><p>Эффективность основана на дате публикации; точных данных по часам в выгрузке нет</p></div><div class="segmented" id="schedule-type"><button data-value="Shorts" class="${STATE.scheduleType==='Shorts'?'active':''}">Shorts</button><button data-value="Видео" class="${STATE.scheduleType==='Видео'?'active':''}">Видео</button></div></div><div class="day-grid">${data.map(x=>`<div class="day-card ${x.day===best.day?'best':x.day===worst.day?'worst':''}"><span>${x.day}</span><strong>${nf.format(Math.round(x.momentum))}</strong><small>просм./день · ${x.published} новых</small></div>`).join('')}</div><div class="grid-2 grid-equal"><article class="card panel">${panelHead('Momentum по дням','скорость набора просмотров')}${barList(data.map(x=>({label:x.day,value:x.momentum})),'value',x=>`${nf.format(Math.round(x))}/д`,7,true)}<div class="insight"><span>★</span><div><strong>Лучший день — ${best.day.toLowerCase()}.</strong><br>Переносите часть публикаций с ${worst.day.toLowerCase()} на сильные дни и проверяйте результат сериями.</div></div></article><article class="card panel">${panelHead('Частота против эффективности','насколько текущий график совпадает со спросом')}<div class="heatmap-wrap"><div class="heat-row"><div></div>${DAYS.map(d=>`<div class="heat-label">${d.slice(0,2)}</div>`).join('')}</div><div class="heat-row"><div class="heat-label">Momentum</div>${data.map(x=>`<div class="heat-cell" style="background:rgba(22,163,106,${.10+.65*x.momentum/maxM});color:${x.momentum/maxM>.55?'#fff':'#14532d'}">${Math.round(x.momentum)}</div>`).join('')}</div><div class="heat-row"><div class="heat-label">Публикации</div>${data.map(x=>`<div class="heat-cell" style="background:rgba(37,99,235,${.10+.65*x.published/maxP});color:${x.published/maxP>.55?'#fff':'#1e3a8a'}">${x.published}</div>`).join('')}</div><div class="heat-row"><div class="heat-label">Retention</div>${data.map(x=>`<div class="heat-cell" style="background:rgba(124,58,237,${.10+.65*x.retention});color:${x.retention>.6?'#fff':'#4c1d95'}">${pct(x.retention,0)}</div>`).join('')}</div></div><p class="muted" style="font-size:10px;margin-top:16px">Для выбора часа публикации запросите в Studio график «Когда ваши зрители смотрят YouTube». Пока тестовая гипотеза: 07:00–09:00 и 18:00–21:00 МСК.</p></article></div>`;
}

function renderGrowth(){
  const w=STATE.data.weak,recs=[['Поднять CTR длинных видео','Обновлять миниатюры и заголовки 5–10 старых роликов в месяц, начиная с топ-30 по просмотрам с CTR ниже 4%.'],['Усилить первые 90 секунд','Перенести основной совет и обещание результата в начало; тестировать видео длиной 12–20 минут.'],['Связать Shorts и видео','Собрать плейлисты по симптомам и перелинковать короткие и длинные форматы через комментарии и описания.'],['Конвертировать охват в базу','Добавить CTA в последние 2 секунды каждого Shorts и закреплённый комментарий со следующим шагом.'],['Расширить темы-кандидаты','Снять по 5+ Shorts о коме в горле, шуме в ушах, шее, физиологии и ЖКТ.'],['Синхронизировать расписание','Перенести полноформатные видео ближе к четвергу и пятнице, Shorts — к выходным и сильным дням.']];
  const tasks=[['Запросить график «Когда ваши зрители на YouTube»','high','Неделя 1'],['Обновить миниатюры топ-30 видео с CTR < 4%','high','Недели 1–4'],['Добавить CTA и закреплённый комментарий в Shorts','high','Неделя 1'],['Снять 5+ Shorts по каждой теме-кандидату','medium','Недели 1–4'],['Собрать тематические плейлисты и перелинковать форматы','medium','Недели 2–3'],['Сместить публикацию видео к четвергу/пятнице','low','Неделя 2']];const done=JSON.parse(localStorage.getItem('yt-growth-tasks')||'[]');
  return`<div class="risk-grid"><article class="card risk-card"><h3>Кликабельность видео</h3><div class="risk-value">${pctRaw(w.videoCtr,2)}</div><div class="gauge"><i style="width:${Math.min(w.videoCtr/8*100,100)}%"></i><em style="left:50%" title="Ориентир 4%"></em></div><p class="risk-note">${pct(w.lowCtrShare,0)} длинных видео ниже ориентира 4%. Медиана Shorts — ${pctRaw(w.shortsCtr,2)}.</p></article><article class="card risk-card"><h3>Удержание видео</h3><div class="risk-value">${pct(w.videoRetention,1)}</div><div class="gauge"><i style="width:${w.videoRetention*100}%;background:#f59e0b"></i><em style="left:40%" title="Ориентир 40%"></em></div><p class="risk-note">${pct(w.lowRetentionShare,0)} видео удерживают меньше 40%. У Shorts медиана ${pct(w.shortsRetention,1)}.</p></article><article class="card risk-card"><h3>Конверсия в подписку</h3><div class="risk-value">${pct(w.conversion,3)}</div><div class="gauge"><i style="width:${Math.min(w.conversion/.0065*100,100)}%;background:#7c3aed"></i><em style="left:77%" title="Ориентир 0,5%"></em></div><p class="risk-note">Видео конвертируют в ${Math.round(w.videoConversion/w.shortsConversion*10)/10} раза лучше Shorts: ${pct(w.videoConversion,3)} против ${pct(w.shortsConversion,3)}.</p></article></div><div class="section-title" style="margin-top:26px"><div><h2>Шесть рычагов роста</h2><p>План собран из всех разделов отчёта</p></div></div><div class="recommendations">${recs.map((r,i)=>`<article class="card recommendation"><div class="rec-number">${i+1}</div><div><h3>${r[0]}</h3><p>${r[1]}</p></div></article>`).join('')}</div><div class="grid-2 grid-equal"><article class="card panel">${panelHead('Чек-лист на 30 дней','прогресс сохраняется в этом браузере')}<div class="checklist">${tasks.map((t,i)=>`<label class="check-item ${done.includes(i)?'done':''}"><input type="checkbox" data-task="${i}" ${done.includes(i)?'checked':''}><span class="check-text"><b>${t[0]}</b><br><span class="muted">${t[2]}</span></span><span class="priority ${t[1]}">${t[1]==='high'?'Высокий':t[1]==='medium'?'Средний':'Низкий'}</span></label>`).join('')}</div></article><article class="card panel">${panelHead('Архив против нового контента','просмотры за 90 дней')}${donut([{label:'Свежий контент',value:w.freshViews90},{label:'Архив',value:w.archiveViews90}])}<div class="insight"><span>!</span><div><strong>${pct(1-w.freshShare,0)} просмотров всё ещё даёт архив.</strong><br>Обновление старых хитов снижает риск их естественного угасания.</div></div></article></div>`;
}

function render(){
  if(!PAGE_META[STATE.page])STATE.page='overview';const [title,eyebrow]=PAGE_META[STATE.page];document.getElementById('page-title').textContent=title;document.getElementById('page-eyebrow').textContent=eyebrow;document.getElementById('report-date').textContent=`Данные на ${fmtDate(STATE.data.meta.asOf)}`;document.getElementById('sidebar-date').textContent=fmtDate(STATE.data.meta.asOf);document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===STATE.page));
  const views={overview:renderOverview,themes:renderThemes,content:renderContent,rhythm:renderRhythm,schedule:renderSchedule,growth:renderGrowth};document.getElementById('page').innerHTML=views[STATE.page]();bindPage();window.scrollTo({top:0,behavior:'instant'});
}
function bindPage(){
  document.getElementById('topic-metric')?.addEventListener('change',e=>{STATE.topicMetric=e.target.value;STATE.selectedTopic=null;render()});document.querySelectorAll('[data-topic]').forEach(b=>b.addEventListener('click',()=>{STATE.selectedTopic=b.dataset.topic;render()}));
  document.querySelectorAll('#content-type button').forEach(b=>b.addEventListener('click',()=>{STATE.contentType=b.dataset.value;render()}));document.getElementById('content-sort')?.addEventListener('change',e=>{STATE.contentSort=e.target.value;render()});document.getElementById('content-search')?.addEventListener('change',e=>{STATE.contentSearch=e.target.value;render()});
  document.querySelectorAll('#schedule-type button').forEach(b=>b.addEventListener('click',()=>{STATE.scheduleType=b.dataset.value;render()}));document.querySelectorAll('[data-task]').forEach(c=>c.addEventListener('change',()=>{const done=[...document.querySelectorAll('[data-task]:checked')].map(x=>Number(x.dataset.task));localStorage.setItem('yt-growth-tasks',JSON.stringify(done));render()}));
}
document.querySelectorAll('.nav button').forEach(b=>b.addEventListener('click',()=>{STATE.page=b.dataset.page;location.hash=STATE.page;document.querySelector('.sidebar').classList.remove('open');render()}));document.querySelector('.mobile-menu').addEventListener('click',()=>document.querySelector('.sidebar').classList.toggle('open'));window.addEventListener('hashchange',()=>{STATE.page=location.hash.slice(1)||'overview';render()});
function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2800)}

// Минимальный локальный XLSX-ридер: обновляет платформу из отчёта той же структуры без отправки файла в сеть.
async function unzipXlsx(buffer){
  const view=new DataView(buffer),bytes=new Uint8Array(buffer);let eocd=-1;for(let i=bytes.length-22;i>=Math.max(0,bytes.length-65557);i--){if(view.getUint32(i,true)===0x06054b50){eocd=i;break}}if(eocd<0)throw new Error('Не найден ZIP-контейнер');const count=view.getUint16(eocd+10,true),offset=view.getUint32(eocd+16,true);let p=offset;const files=new Map();
  for(let i=0;i<count;i++){if(view.getUint32(p,true)!==0x02014b50)break;const method=view.getUint16(p+10,true),size=view.getUint32(p+20,true),nameLen=view.getUint16(p+28,true),extraLen=view.getUint16(p+30,true),commentLen=view.getUint16(p+32,true),local=view.getUint32(p+42,true),name=new TextDecoder().decode(bytes.slice(p+46,p+46+nameLen));files.set(name,{method,size,local});p+=46+nameLen+extraLen+commentLen}
  async function read(name){const f=files.get(name);if(!f)throw new Error(`В книге нет ${name}`);const nl=view.getUint16(f.local+26,true),el=view.getUint16(f.local+28,true),start=f.local+30+nl+el,chunk=bytes.slice(start,start+f.size);if(f.method===0)return chunk;if(f.method!==8)throw new Error('Неподдерживаемое сжатие XLSX');const ds=new DecompressionStream('deflate-raw'),out=await new Response(new Blob([chunk]).stream().pipeThrough(ds)).arrayBuffer();return new Uint8Array(out)}return{files,read};
}
const xmlText=bytes=>new TextDecoder('utf-8').decode(bytes);const xmlDoc=bytes=>new DOMParser().parseFromString(xmlText(bytes),'application/xml');
function colIndex(ref){let n=0;for(const c of ref.match(/[A-Z]+/i)?.[0]||'A')n=n*26+c.toUpperCase().charCodeAt(0)-64;return n-1}
async function readWorkbook(file){
  const zip=await unzipXlsx(await file.arrayBuffer()),wb=xmlDoc(await zip.read('xl/workbook.xml')),rels=xmlDoc(await zip.read('xl/_rels/workbook.xml.rels'));const relMap=new Map([...rels.getElementsByTagName('Relationship')].map(r=>[r.getAttribute('Id'),r.getAttribute('Target')]));let shared=[];if(zip.files.has('xl/sharedStrings.xml')){const sx=xmlDoc(await zip.read('xl/sharedStrings.xml'));shared=[...sx.getElementsByTagName('si')].map(si=>[...si.getElementsByTagName('t')].map(t=>t.textContent).join(''))}
  const sheets=new Map();for(const sh of wb.getElementsByTagName('sheet')){const name=sh.getAttribute('name'),rid=sh.getAttribute('r:id')||sh.getAttributeNS('http://schemas.openxmlformats.org/officeDocument/2006/relationships','id'),target=relMap.get(rid);if(!target)continue;const path=target.startsWith('/')?target.slice(1):`xl/${target.replace(/^\.\//,'')}`,doc=xmlDoc(await zip.read(path)),rows=[];for(const row of doc.getElementsByTagName('row')){const arr=[];for(const c of row.getElementsByTagName('c')){const idx=colIndex(c.getAttribute('r')),type=c.getAttribute('t'),v=c.getElementsByTagName('v')[0]?.textContent??'',inline=[...c.getElementsByTagName('t')].map(t=>t.textContent).join('');let value=type==='s'?shared[Number(v)]:(type==='inlineStr'?inline:(type==='str'?v:(v===''?'':Number(v))));arr[idx]=value}rows.push(arr)}sheets.set(name,rows)}return sheets;
}
function excelIso(serial){return new Date(Date.UTC(1899,11,30)+Number(serial)*86400000).toISOString().slice(0,10)}
function parse365Rows(rows){return rows.slice(3).filter(r=>r[0]).map(r=>({id:r[0],title:r[1],type:r[2],published:excelIso(r[3]),duration:+r[4]||0,impressions:+r[5]||0,ctr:+r[6]||0,views:+r[7]||0,avgView:+r[8]||0,watchHours:+r[9]||0,topic:r[10]||'Другое',retention:+r[11]||0,weekday:r[12]||'',ageDays:+r[13]||0,momentum:+r[14]||0}))}
function parse90Rows(rows){return rows.slice(3).filter(r=>r[0]).map(r=>({id:r[0],title:r[1],type:r[2],published:excelIso(r[3]),duration:+r[4]||0,impressions:+r[5]||0,ctr:+r[6]||0,views:+r[7]||0,subscribers:+r[8]||0,watchHours:+r[9]||0,weekday:r[10]||'',ageDays:+r[11]||0,fresh:r[12]==='Да'}))}
document.getElementById('xlsx-input').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;const status=document.getElementById('upload-status');status.textContent='Читаю и пересчитываю…';try{const s=await readWorkbook(file);for(const name of ['Видео 365 дней','Shorts 365 дней','Контент 90 дней'])if(!s.has(name))throw new Error(`Нет листа «${name}»`);STATE.data={...STATE.data,videos365:parse365Rows(s.get('Видео 365 дней')),shorts365:parse365Rows(s.get('Shorts 365 дней')),content90:parse90Rows(s.get('Контент 90 дней'))};const p=s.get('Параметры');if(p){STATE.data.meta={...STATE.data.meta,channel:p[3]?.[1]||STATE.data.meta.channel,asOf:p[4]?.[1]?excelIso(p[4][1]):STATE.data.meta.asOf,subscribers:+p[5]?.[1]||STATE.data.meta.subscribers};STATE.data.studio90={views:+p[14]?.[1]||STATE.data.studio90.views,viewsDelta:p[14]?.[2]||'',watchHours:+p[15]?.[1]||STATE.data.studio90.watchHours,watchDelta:p[15]?.[2]||'',subscribers:+p[16]?.[1]||STATE.data.studio90.subscribers,subscribersDelta:p[16]?.[2]||''}}status.textContent=`Загружено: ${file.name}`;toast('Отчёт обновлён и пересчитан');render()}catch(err){console.error(err);status.textContent='Не удалось прочитать этот файл';toast(`Ошибка: ${err.message}`)}finally{e.target.value=''}});

let connectionPoll=null;
function renderConnection(status){
  const box=document.getElementById('connection-card');if(!box)return;
  if(!status){box.innerHTML='<strong class="error">Сервер недоступен</strong><span>Запустите приложение через сервер</span>';return}
  if(!status.connected){box.innerHTML='<strong>YouTube не подключён</strong><span>Требуется однократный вход Google</span><a href="/api/auth/google">Подключить YouTube</a>';return}
  const sync=status.sync||{state:'idle'},label=sync.state==='syncing'?'Синхронизация…':sync.state==='error'?'Ошибка синхронизации':'YouTube подключён';
  const quotaError=/exceeded your quota/i.test(sync.message||'');
  const detail=sync.state==='ready'?`${sync.videoCount||0} роликов · данные актуальны`:sync.state==='error'?(quotaError?'Суточная квота YouTube Data API пока не восстановлена. Повторите позже.':(sync.message||'Повторите синхронизацию')):(status.channel?.title||'Канал авторизован');
  box.innerHTML=`<strong class="${sync.state==='error'?'error':'connected'}">${esc(label)}</strong><span>${esc(detail)}</span><button type="button" id="sync-youtube" ${sync.state==='syncing'?'disabled':''}>${sync.state==='syncing'?'Обновляю…':'Синхронизировать'}</button>`;
  document.getElementById('sync-youtube')?.addEventListener('click',syncYouTube);
}
async function loadLiveData(){
  const response=await fetch('/api/live-data',{cache:'no-store'});if(!response.ok)return false;const data=await response.json();
  STATE.data={...STATE.data,...data,weak:{...STATE.data.weak,...data.weak}};
  document.querySelector('.channel-card strong').textContent=(data.meta.channel||'YouTube').split(' (')[0];
  document.querySelector('.channel-card span').textContent=`${data.meta.channelId||''} · ${shortN(data.meta.subscribers)} подписчиков`;
  render();return true;
}
async function refreshConnection(){
  if(REVIEW_MODE){document.getElementById('connection-card').innerHTML='<strong class="connected">Compliance review</strong><span>Demo data · live OAuth in private deployment</span>';return}
  try{const response=await fetch('/api/status',{cache:'no-store'});if(!response.ok)throw new Error('status');const status=await response.json();renderConnection(status);if(status.connected&&status.sync?.state==='ready')await loadLiveData();
    if(status.sync?.state==='syncing'){clearTimeout(connectionPoll);connectionPoll=setTimeout(refreshConnection,2000)}
  }catch{renderConnection(null)}
}
async function syncYouTube(){
  const button=document.getElementById('sync-youtube');if(button){button.disabled=true;button.textContent='Запускаю…'}
  try{const response=await fetch('/api/sync',{method:'POST'});if(!response.ok)throw new Error('Не удалось запустить синхронизацию');toast('Синхронизация YouTube запущена');setTimeout(refreshConnection,900)}catch(error){toast(error.message);refreshConnection()}
}

render();
refreshConnection();
